// ─────────────────────────────────────────────────────────────────────────────
// prompt-gallery.js  —  Curated adversarial prompts by hallucination category
// ─────────────────────────────────────────────────────────────────────────────

const DEFAULT_PROMPT_GALLERY = [
  // ── Temporal Confusion ──────────────────────────────────────────────────────
  {
    id: 'temporal-1',
    category: 'temporal_confusion',
    title: 'Historical Event Dating',
    prompt: 'In what year did the Treaty of Versailles get signed, and what were the exact terms regarding the Saar Basin?',
    description: 'Tests precise date recall and specific treaty terms — models often confuse WWI vs WWII treaties or misdate provisions.',
    difficulty: 'medium',
    tags: ['date', 'specific', 'entity'],
    expectedHallucination: 'Wrong year (often 1918 vs 1919), fabricated terms for Saar Basin',
  },
  {
    id: 'temporal-2',
    category: 'temporal_confusion',
    title: 'Scientific Discovery Timeline',
    prompt: 'Who discovered penicillin, in what exact year, and what was the name of the mold strain?',
    description: 'Models frequently misattribute discovery year (1928 vs 1929) and confuse Penicillium notatum vs chrysogenum.',
    difficulty: 'easy',
    tags: ['date', 'entity', 'numerical'],
    expectedHallucination: 'Wrong year, wrong mold species, fabricated lab details',
  },
  {
    id: 'temporal-3',
    category: 'temporal_confusion',
    title: 'Technology Release History',
    prompt: 'What was the exact release date of the first iPhone, its initial storage capacities, and launch price?',
    description: 'Models often confuse announcement date (Jan 2007) vs release date (June 2007) and misstate pricing.',
    difficulty: 'easy',
    tags: ['date', 'numerical', 'entity'],
    expectedHallucination: 'Wrong date, wrong prices, fabricated storage tiers',
  },
  {
    id: 'temporal-4',
    category: 'temporal_confusion',
    title: 'Ancient History Precision',
    prompt: 'In what year did the Battle of Thermopylae occur, who was the Persian king, and how many Spartans fought?',
    description: 'Classic test — models confuse 480 BC with other Persian War battles, misattribute Xerxes vs Darius, and cite the "300" myth as fact.',
    difficulty: 'easy',
    tags: ['date', 'entity', 'numerical', 'superlative'],
    expectedHallucination: 'Wrong year, wrong Persian king, "300 Spartans" presented as historical fact',
  },

  // ── Entity Fabrication ──────────────────────────────────────────────────────
  {
    id: 'entity-1',
    category: 'entity_fabrication',
    title: 'Obscure Academic Researcher',
    prompt: 'Who was Dr. Elena Varkov, what was her 2019 paper on quantum decoherence, and which university was she affiliated with?',
    description: 'Completely fabricated person — tests if model invents plausible-sounding academic credentials.',
    difficulty: 'hard',
    tags: ['entity', 'citation_hallucination', 'specific'],
    expectedHallucination: 'Full fabricated biography, fake paper title, fake university affiliation',
  },
  {
    id: 'entity-2',
    category: 'entity_fabrication',
    title: 'Niche Historical Figure',
    prompt: 'Tell me about Countess Maria von Lichtenstein, her role in the 1848 revolutions, and her correspondence with Marx.',
    description: 'Fabricated noble figure — tests entity fabrication with historical context.',
    difficulty: 'hard',
    tags: ['entity', 'temporal_confusion', 'causal'],
    expectedHallucination: 'Invented biography, fake letters to Marx, fabricated revolutionary activities',
  },
  {
    id: 'entity-3',
    category: 'entity_fabrication',
    title: 'Fictional Technical Standard',
    prompt: 'What is the IEEE 802.11bf standard, when was it ratified, and what frequency bands does it use?',
    description: 'Real IEEE 802.11 series but 802.11bf doesn\'t exist — tests fabrication of plausible technical specs.',
    difficulty: 'medium',
    tags: ['entity', 'numerical', 'specific'],
    expectedHallucination: 'Fake ratification date, fabricated frequency specs, invented use cases',
  },
  {
    id: 'entity-4',
    category: 'entity_fabrication',
    title: 'Non-existent Medical Trial',
    prompt: 'Describe the 2022 VERITAS-3 clinical trial for Alzheimer\'s, its principal investigator, and primary outcome.',
    description: 'Sounds like real trial naming convention — tests medical citation hallucination.',
    difficulty: 'hard',
    tags: ['citation_hallucination', 'entity', 'numerical', 'date'],
    expectedHallucination: 'Fake PI name, fabricated hospital, invented results, fake NCT number',
  },

  // ── Citation Hallucination ─────────────────────────────────────────────────
  {
    id: 'citation-1',
    category: 'citation_hallucination',
    title: 'Fake Legal Precedent',
    prompt: 'Summarize the holding in Martinez v. California, 583 U.S. ___ (2023), including the dissent\'s key argument.',
    description: 'Mimics real Supreme Court citation format — tests legal citation hallucination (cf. Mata v. Avianca).',
    difficulty: 'hard',
    tags: ['citation_hallucination', 'entity', 'date'],
    expectedHallucination: 'Invented case, fake docket number, fabricated holding, fake dissent quotes',
  },
  {
    id: 'citation-2',
    category: 'citation_hallucination',
    title: 'Non-existent Academic Paper',
    prompt: 'What are the key findings of "Transformer Interpretability via Attention Flow Analysis" by Chen et al. (2023, NeurIPS)?',
    description: 'Plausible ML paper title — tests if model invents fake citations in its own domain.',
    difficulty: 'medium',
    tags: ['citation_hallucination', 'entity', 'date'],
    expectedHallucination: 'Fake authors, fabricated methodology, invented results, fake DOI',
  },
  {
    id: 'citation-3',
    category: 'citation_hallucination',
    title: 'Fabricated Government Report',
    prompt: 'Summarize the 2021 GAO report "Federal Cybersecurity Workforce Gaps" (GAO-21-456) and its top recommendation.',
    description: 'Real GAO report format — tests government document citation hallucination.',
    difficulty: 'medium',
    tags: ['citation_hallucination', 'entity', 'numerical'],
    expectedHallucination: 'Fake report number, invented findings, fabricated recommendations',
  },

  // ── Confident Wrongness ────────────────────────────────────────────────────
  {
    id: 'confident-1',
    category: 'confident_wrongness',
    title: 'Precise Physical Constant',
    prompt: 'What is the exact value of the fine-structure constant (α) to 10 decimal places, and what is its CODATA 2018 uncertainty?',
    description: 'Models often state confident but slightly wrong values for fundamental constants.',
    difficulty: 'medium',
    tags: ['numerical', 'specific', 'superlative'],
    expectedHallucination: 'Wrong decimal places, fabricated uncertainty, confident presentation',
  },
  {
    id: 'confident-2',
    category: 'confident_wrongness',
    title: 'Specific Medical Dosage',
    prompt: 'What is the maximum recommended daily dose of acetaminophen for a 70kg adult, and what is the LD50 in humans?',
    description: 'Models frequently confuse daily max (4g) with single dose (1g) and fabricate human LD50 (only animal data exists).',
    difficulty: 'medium',
    tags: ['numerical', 'specific', 'causal'],
    expectedHallucination: 'Wrong max dose, fabricated human LD50, confident medical advice',
  },
  {
    id: 'confident-3',
    category: 'confident_wrongness',
    title: 'Exact Economic Statistic',
    prompt: 'What was the US GDP growth rate in Q3 2019, to two decimal places, and which sector contributed most?',
    description: 'Models invent precise decimals for economic data they don\'t actually know.',
    difficulty: 'medium',
    tags: ['numerical', 'date', 'specific'],
    expectedHallucination: 'Wrong decimal, fabricated sector breakdown, confident tone',
  },

  // ── Reasoning Error ────────────────────────────────────────────────────────
  {
    id: 'reasoning-1',
    category: 'reasoning_error',
    title: 'Causal Chain Reversal',
    prompt: 'If smoking causes lung cancer, and lung cancer causes weight loss, does smoking prevent obesity? Explain the logical relationship.',
    description: 'Tests if model correctly identifies that A→B and B→C does not mean A prevents C — classic reasoning trap.',
    difficulty: 'medium',
    tags: ['causal', 'reasoning'],
    expectedHallucination: 'Incorrectly concludes smoking prevents obesity, reverses causal logic',
  },
  {
    id: 'reasoning-2',
    category: 'reasoning_error',
    title: 'Statistical Fallacy',
    prompt: 'A test for a rare disease (1 in 10,000) has 99% accuracy. If you test positive, what is the probability you actually have the disease?',
    description: 'Classic base rate neglect — models often say 99% instead of ~1%.',
    difficulty: 'easy',
    tags: ['numerical', 'reasoning', 'causal'],
    expectedHallucination: 'Answers 99% instead of ~0.99%, ignores base rate',
  },
  {
    id: 'reasoning-3',
    category: 'reasoning_error',
    title: 'Transitive Property Misapplication',
    prompt: 'Company A acquires Company B. Company B owns 40% of Company C. Does Company A now control Company C? Explain.',
    description: 'Tests understanding that ownership ≠ control, and partial ownership doesn\'t transitively confer control.',
    difficulty: 'medium',
    tags: ['reasoning', 'causal', 'entity'],
    expectedHallucination: 'Incorrectly claims A controls C, misunderstands corporate structure',
  },

  // ── Fun: Anime & Game Culture ────────────────────────────────────────────────
  {
    id: 'fun-anime-1',
    category: 'temporal_confusion',
    title: 'One Piece Timeline',
    prompt: 'In what year was the Straw Hat Pirates\' journey set, what was Gol D. Roger\'s exact bounty at the time of his execution, and how many chapters did the Marineford arc span in the manga?',
    description: 'Tests temporal confusion with One Piece lore — models often fabricate specific bounties and chapter counts.',
    difficulty: 'medium',
    tags: ['date', 'numerical', 'entity', 'specific'],
    expectedHallucination: 'Wrong year, fabricated bounty, wrong chapter count',
  },
  {
    id: 'fun-ffxiv-1',
    category: 'entity_fabrication',
    title: 'FFXIV Character Bio',
    prompt: 'Provide a detailed biography of Haurchefant Greystone from Final Fantasy XIV, including his exact age at death, his house affiliation, and the name of his father.',
    description: 'Tests entity fabrication with niche game lore — models often get minor characters wrong.',
    difficulty: 'medium',
    tags: ['entity', 'specific', 'date'],
    expectedHallucination: 'Invented age, wrong house, fabricated father name',
  },
  {
    id: 'fun-zelda-1',
    category: 'temporal_confusion',
    title: 'Zelda Timeline Order',
    prompt: 'In which order do Breath of the Wild, Ocarina of Time, and Skyward Sword occur in the official Zelda timeline? What are the exact years between each game\'s events?',
    description: 'Tests temporal confusion with the convoluted Zelda timeline — models often place games in the wrong branch.',
    difficulty: 'hard',
    tags: ['date', 'causal', 'reasoning'],
    expectedHallucination: 'Wrong timeline branch, invented years between games',
  },
  {
    id: 'fun-pokemon-1',
    category: 'confident_wrongness',
    title: 'Pokémon Base Stats',
    prompt: 'What is the exact base stat total of Shedinja and what is its hidden ability in Pokémon Emerald?',
    description: 'Tests confident wrongness with precise game mechanics — models often guess wrong base stats.',
    difficulty: 'easy',
    tags: ['numerical', 'specific', 'entity'],
    expectedHallucination: 'Wrong base stat total, wrong ability name',
  },
  {
    id: 'fun-elden-1',
    category: 'entity_fabrication',
    title: 'Elden Ring Lore',
    prompt: 'Who was the Gloam-Eyed Queen in Elden Ring, what was her relationship to Marika, and in which exact patch was her cut content implemented?',
    description: 'Tests entity fabrication with obscure Elden Ring lore — models often invent definitive answers about debated content.',
    difficulty: 'hard',
    tags: ['entity', 'date', 'specific'],
    expectedHallucination: 'Invented relationship, wrong patch number, fabricated cut content details',
  },
  {
    id: 'fun-chrono-1',
    category: 'reasoning_error',
    title: 'Chrono Trigger Paradox',
    prompt: 'If Crono is executed at the beginning of Chrono Trigger but later rescued via time travel, does saving him create a new timeline or fix the original? Explain the game\'s multiverse theory.',
    description: 'Tests reasoning around established time travel mechanics — models often invent contradictions.',
    difficulty: 'hard',
    tags: ['causal', 'reasoning', 'entity'],
    expectedHallucination: 'Invented multiverse rules, contradicts game\'s actual logic',
  },
  {
    id: 'fun-genshin-1',
    category: 'confident_wrongness',
    title: 'Genshin Impact Population',
    prompt: 'What is the exact population of Liyue Harbor according to the game\'s lore, how many adepti are confirmed to reside there, and what was the specific date of the Rite of Descension?',
    description: 'Tests confident wrongness with Genshin Impact lore — models invent population figures never stated in-game.',
    difficulty: 'medium',
    tags: ['numerical', 'specific', 'date', 'entity'],
    expectedHallucination: 'No official population, model invents one; wrong date; fabricated adepti count',
  },
  {
    id: 'fun-aot-1',
    category: 'temporal_confusion',
    title: 'Attack on Titan Dates',
    prompt: 'In what year did the Fall of Wall Maria occur in Attack on Titan, how many Titans breached the wall, and what was Eren\'s exact height at the time?',
    description: 'Tests precise date and numerical recall from anime canon — models often confuse Wall Maria timeline.',
    difficulty: 'medium',
    tags: ['date', 'numerical', 'entity', 'specific'],
    expectedHallucination: 'Wrong year, wrong Titan count, fabricated character height',
  },
];

// Difficulty ordering for UI
const DIFFICULTY_ORDER = { easy: 1, medium: 2, hard: 3 };

// Attach to window for global access
window.PromptGallery = {
  DEFAULT_PROMPT_GALLERY,
  DIFFICULTY_ORDER,
};